name: Deploy site

on: workflow_dispatch
  # push:
  #   branches: release

jobs:
  build-deploy:
    name: "Build and deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true

      - name: Set up dependencies
        run: |
          gem update --system --no-document
          gem update bundler --no-document
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle clean

      - name: Clone target branch
        run: |
          REMOTE_BRANCH="${REMOTE_BRANCH:-master}"
          REMOTE_REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          echo "Publishing to ${GITHUB_REPOSITORY} on branch ${REMOTE_BRANCH}"
          rm -rf _site/
          git clone --depth=1 --branch="${REMOTE_BRANCH}" --single-branch --no-checkout \
            "${REMOTE_REPO}" _site/
        
      - name: Build
        run: JEKYLL_ENV=production bundle exec jekyll build --verbose --trace

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: master
          cname: mitevstefan.com