name: Deploy site

on: workflow_dispatch
  # push:
  #   branches: release

jobs:
  build-deploy:
    name: "Build and deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true
          
      - name: Build
        run: JEKYLL_ENV=production bundle exec jekyll build --trace

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: master
          cname: mitevstefan.com